#ifndef __GAME_WORKAROUNDS_H
#define __GAME_WORKAROUNDS_H
enum GAME_WORKAROUND_ACTION{
    GAME_WORKAROUND_ACTION_VERTICE_PROCESSED,
    GAME_WORKAROUND_ACTION_VERTICE_NOT_PROCESSED,
    GAME_WORKAROUND_ACTION_NOP,
};

enum GAME_WORKAROUND_ACTION fix_prim(int vertex_count, int prim);
#endif
